baseurl = "https://luciarodrigoinsausti.com/SAStutorial/"
languageCode = "en-us"
title = "Learning SAS"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
# googleAnalytics = ""

[params]
	# General information
	# author = "Digitalcraftsman"
	# description = "A material design theme for documentations."
	# copyright = "Released under the MIT license"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	#version = "1.0.0"
	logo = "images/sas-logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	 highlight_css  = "stylesheets/prisma-sas.css"
	# highlight_js  = "javascripts/prisma-sas.js"

	[params.palette]
    	primary = "indigo"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	# twitter = ""
	# github  = "digitalcraftsman"
	# email   = "hello@email.com"

[[menu.main]]
	name   = "SAS Programming Essentials"
	url    = "essential/"
	weight = 10

[[menu.main]]
	name   = "Statistics"
	url    = "statistics/"
	weight = 20

[[menu.main]]
	name   = "Missing Data"
	url    = "missing_data/"
	weight = 30

[[menu.main]]
	name   = "Using Macros"
	url    = "macros/"
	weight = 40

[[menu.main]]
	name   = "Miscellanea"
	url    = "miscellanea/"
	weight = 50


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
